/**********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 *********************************************************************************************************************/
/**********************************************************************************************************************
 * Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *********************************************************************************************************************/

#include "common_utils.h"
#include "ext_irq_setup.h"
#include "hal_data.h"
#include "timer_setup.h"

#define SYS_CPU_FREEZEEN_DISABLE        (0U)
#define SYS_CPU_FREEZEEN_ENABLE         (1U)

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*
 * private function declarations
 */
/* function used to read RTT input and proceed */
static fsp_err_t read_Input_from_RTT(void);
/* function used to enable wdog in debug mode */
static void enable_wdog_count_in_debug_mode(void);
/* function used to check if reset is caused by watchdog or not */
static void check_reset_status(void);
/* function used to configure GPIOs that are connected to LEDs */
static void initialize_led_pin(void);

/*********************************************************************************************************************
 * This function is called to configure GPIO that is connected to LED.
 * @brief    Configure GPIO as output pin.
 * @param[IN]   None
 * @retval      None
 **********************************************************************************************************************/
static void initialize_led_pin(void)
{
    R_GPIO_W_PinCfg(&g_ioport_ctrl, LED_POR_AND_TIMER_ACTIVE_IND, IOPORT_CFG_PORT_DIRECTION_OUTPUT);
    R_GPIO_W_PinCfg(&g_ioport_ctrl, LED_WATCHDOG_RESET_IND, IOPORT_CFG_PORT_DIRECTION_OUTPUT);
}

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_pack_version_t version = {RESET_VALUE};
    fsp_err_t err = FSP_SUCCESS;

    /* Version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Example Project information printed on the Console */
    APP_PRINT(BANNER_1);
    APP_PRINT(BANNER_2);
    APP_PRINT(BANNER_3, EP_VERSION);
    APP_PRINT(BANNER_4, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(BANNER_5);
    APP_PRINT(BANNER_6);

    APP_PRINT("\r\nThis example project demonstrates the typical use of the WDOG HAL module APIs");
    APP_PRINT("\r\nUser input initializes the WDOG and start GPT timer");
    APP_PRINT("\r\nWDOG counter is refreshed periodically every 1 second when the GPT timer expires");
    APP_PRINT("\r\nOn pressing the BTN1 Push button, WDOG counter stops from refreshing");
    APP_PRINT("\r\nWDOG resets the device in 3 seconds\r\n");

    initialize_led_pin();
    check_reset_status();

    /* Initializing GPT in PWM Mode */
    err = init_gpt_module();
    if (FSP_SUCCESS != err)
    {
        /* Timer initialization failed */
        APP_ERR_PRINT("\r\n ** GPT TIMER INIT FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    /* Initializing External IRQ */
    err = init_icu_module();
    if (FSP_SUCCESS != err)
    {
        /* External IRQ initialization failed, cleanup the timer initialization */
        APP_ERR_PRINT("\r\n ** EXTERNAL IRQ INIT FAILED ** \r\n");
        deinit_gpt_module();
        APP_ERR_TRAP(err);
    }

    /* Menu for User Selection */
    APP_PRINT("\r\nEnter 1 to Enable WDOG\r\n");
    APP_PRINT("User Input:  ");

    while (true)
    {
        /* Process input only when User has provided one */
        if (APP_CHECK_DATA)
        {
            err = read_Input_from_RTT();
            if (FSP_SUCCESS != err)
            {
                /* Close timer and external IRQ module */
                deinit_gpt_module();
                deinit_icu_module();
                APP_ERR_TRAP(err);
            }
        }
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* Configure pins. */
        IOPORT_CFG_OPEN(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
    }
}

/***********************************************************************************************************************
 * This function is called to read user input from RTT using RTT API.
 * @brief    Read user input from RTT. Handle the Error internally with Proper Message. Application handles the rest.
 * @param[IN]   None
 * @retval      Any Other Error code apart from FSP_SUCCES  Unsuccessful to perform operation
 **********************************************************************************************************************/
static fsp_err_t read_Input_from_RTT(void)
{
    fsp_err_t err = FSP_SUCCESS;     // Error status

    /* Variable to store user input */
    uint8_t rByte[BUFFER_SIZE] = {RESET_VALUE};
    uint8_t user_data = RESET_VALUE;

    /* Read First byte of data provided by user */
    APP_READ(rByte);

    user_data = (uint8_t) atoi((char*) &rByte);

    switch (user_data)
    {
        case ENABLE_WDOG:
        {
            R_GPIO_W_PinWrite(&g_ioport_ctrl, LED_POR_AND_TIMER_ACTIVE_IND, BSP_IO_LEVEL_LOW);
            R_GPIO_W_PinWrite(&g_ioport_ctrl, LED_WATCHDOG_RESET_IND, BSP_IO_LEVEL_LOW);

            /* Enable WDOG to count and generate NMI or Reset when the debugger(JLink) is connected. */
            enable_wdog_count_in_debug_mode();

            /* Open WDOG. For every GPT timeout, watchdog will get refreshed. */
            err = R_WDOG_W_Open(&g_wdog_ctrl, &g_wdog_cfg);
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("\r\n ** R_WDOG_W_Open API Failed ** \r\n");

                return err;
            }

            /* Start GPT timer in Periodic mode */
            err = timer_start();
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("\r\n ** GPT TIMER START FAILED ** \r\n");

                return err;
            }

            /* Enable External IRQ */
            err = enable_icu_module();
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("\r\n ** EXTERNAL IRQ ENABLE FAILED ** \r\n");

                return err;
            }

            /* Print message to indicate user about application status. */
            APP_PRINT("\r\nWDOG initialized, GPT Timer Started\r\n")
            APP_PRINT("To stop WDOG counter from refreshing, press the push button\r\n");
            break;
        }

        default:
        {
            /* Menu for User Selection */
            APP_PRINT("\r\nInvalid Input");
            APP_PRINT("\r\nPlease provide input from below option");
            APP_PRINT("\r\nEnter 1 to Enable WDOG\r\n");
            APP_PRINT("User Input:  ");
            break;
        }
    }

    user_data = RESET_VALUE;

    return err;
}

/***********************************************************************************************************************
 * This function is called to enable WDOG counter in debug mode.
 * @brief    Enables WDOG counter to count in debug mode.
 * @param[IN]   None
 * @retval      None
 **********************************************************************************************************************/
static void enable_wdog_count_in_debug_mode(void)
{
    /* Clear the SYS_CPU_FREEZE_EN bit.
     * If 1, freezing of the on-chip peripherals is enabled when the Cortex-M33 is halted in DEBUG State */
    GPREG->DEBUG_REG_b.SYS_CPU_FREEZE_EN = SYS_CPU_FREEZEEN_DISABLE;
}

/***********************************************************************************************************************
 * This function is called to check whether reset is caused by WDOG.
 * @brief    Check if reset caused by WDOG or not.
 * @param[IN]   None
 * @retval      None
 **********************************************************************************************************************/
static void check_reset_status(void)
{
    if (RESET_STATUS_REGISTER_POR_DEFAULT == CRG_TOP->RESET_STAT_REG)
    {
        /* Clear the RESET_STAT_REG register */
        CRG_TOP->RESET_STAT_REG = 0;

        /* Turn ON LED */
        R_GPIO_W_PinWrite(&g_ioport_ctrl, LED_POR_AND_TIMER_ACTIVE_IND, BSP_IO_LEVEL_HIGH);
        APP_PRINT("\r\n************* POR Reset detected ************************\r\n");
    }

    if (RESET_STATUS_REGISTER_DETECT_WDOG_RESET == CRG_TOP->RESET_STAT_REG_b.M33_WDOG_STAT)
    {
        /* Turn ON LED */
        R_GPIO_W_PinWrite(&g_ioport_ctrl, LED_WATCHDOG_RESET_IND, BSP_IO_LEVEL_HIGH);
        APP_PRINT("\r\n************** WDOG_RESET Reset detected *****************\r\n");
    }
}

#if BSP_TZ_SECURE_BUILD
FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function
 * in order to build (Remove this if it is not required to build).
 */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{
}
FSP_CPP_FOOTER
#endif
