/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
 *
 * SPDX-License-Identifier: BSD-3-Clause
 ***********************************************************************************************************************/

#include "common_utils.h"
#include "qspi_ep.h"
#include "uart_ep.h"
#include "hal_data.h"

#define LOG_ERR  printf_err
#define LOG_INFO printf_info

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*
 * private functions
 */
void printf_err(char *p_msg);
void printf_info(char *p_msg);

/*
 ******************************************************
 * Usage : declaration user instance, 
 * open -> read/write -> close, then open -> ... > close
 *******************************************************
 */
static fsp_err_t open_qspi(void);
static void close_qspi(void);

ospi_w_instance_ctrl_t user_ospi_ctrl;

void uart_log(char *p_msg)
{
#ifdef ENABLE_UART_LOG
    fsp_err_t err = uart_print_user_msg((uint8_t*) p_msg);
    if (FSP_SUCCESS != err && FSP_ERR_TIMEOUT != err)
    {
        APP_PRINT("\r\n ** UART LOG Print error (%d)** \r\n", err);
    }
#endif
}

void printf_err(char *p_msg)
{
    uart_log(p_msg);

    APP_ERR_PRINT(p_msg);
}

void printf_info(char *p_msg)
{
    uart_log(p_msg);

    APP_PRINT(p_msg);
}
/*******************************************************************************************************************//**
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    uint8_t data_write[PAGE_WRITE_SIZE] = {RESET_VALUE,};
    uint8_t verify_written_data[PAGE_WRITE_SIZE] = {RESET_VALUE,};
    fsp_pack_version_t version = {RESET_VALUE};

    /* Version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Example Project information printed on the Console */
    APP_PRINT(BANNER_1);
    APP_PRINT(BANNER_2);
    APP_PRINT(BANNER_3, EP_VERSION);
    APP_PRINT(BANNER_4, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(BANNER_5);
    APP_PRINT(BANNER_6);

#ifdef ENABLE_UART_LOG
    APP_PRINT("\r\nThe project initializes the UART with baud rate of 115200 bps.");
    APP_PRINT("\r\nOpen Serial Terminal with this baud rate value\r\n\r\n");

    /* Initializing UART */
    err = uart_initialize();
    if (FSP_SUCCESS != err)
    {
        LOG_ERR("\r\n ** UART INIT FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }
    uart_log("\r\n** "MODULE_NAME" example started **\r\n\r\n");
#endif

    /* Open Flash_HP */
    err = open_qspi();
    if (FSP_SUCCESS != err)
    {
        LOG_ERR("Flah_HP_Open API failed\r\n");
        goto end_of_function;
    }

    /* Erase flash before writing */
    err = R_OSPI_W_Erase(&user_ospi_ctrl, QSPI_FLASH_ADDRESS(PAGE_FIRST),
    FLASH_SECTOR_SIZE);
    if (FSP_SUCCESS != err)
    {
        LOG_ERR("R_OSPI_W_Erase Failed\r\n");
        APP_ERR_TRAP(err);
        goto close_module;
    }

    /* Fill the data write buffer further to be written in QSPI flash device */
    for (uint16_t write_index = RESET_VALUE; write_index < PAGE_WRITE_SIZE; write_index++)
    {
        data_write[write_index] = (uint8_t) write_index;
    }

#ifdef ENABLE_DATA_VERIFICATION_LOG
    APP_PRINT("\r\n data_write: %02X %02X %02X ...\r\n", data_write[0], data_write[1], data_write[2]);
#endif

    /* Write data to QSPI Flash */
    err = R_OSPI_W_Write(&user_ospi_ctrl, data_write, (uint8_t*) QSPI_FLASH_ADDRESS(PAGE_FIRST), PAGE_WRITE_SIZE);
    if (FSP_SUCCESS != err)
    {
        LOG_ERR("R_OSPI_W_Write Failed\r\n");
        APP_ERR_TRAP(err);
        goto close_module;
    }

    /* Read data from QSPI memory region */
    memcpy(verify_written_data, QSPI_FLASH_READ_ADDR(PAGE_FIRST), PAGE_WRITE_SIZE);

#ifdef ENABLE_DATA_VERIFICATION_LOG
    APP_PRINT("\r\n written_data: %02X %02X %02X ...\r\n",
              verify_written_data[0], verify_written_data[1], verify_written_data[2]);
#endif

    /* Verify the written data */
    if (FSP_SUCCESS == (fsp_err_t) (memcmp(verify_written_data, data_write, PAGE_WRITE_SIZE)))
    {
        LOG_INFO("\r\n ** Data read matches with written data ** \r\n");
    }
    else
    {
        LOG_ERR("\r\nQSPI operation Failed: not match with written data\r\n");
    }

    close_module :
    /* close QSPI module */
    close_qspi();

    end_of_function :
    LOG_INFO("\r\n ** demo ends here **\r\n\r\n");
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */
        /* Configure pins. */
        IOPORT_CFG_OPEN(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
    }
}

/*******************************************************************************************************************//**
 *  @brief       Open/Close QSPI module
 *  @param[IN]   spi_protocol mode
 *  @retval      None
 **********************************************************************************************************************/
static fsp_err_t open_qspi(void)
{
    fsp_err_t err = FSP_SUCCESS;

    LOG_INFO("\r\n ** Open QSPI module ** \r\n");

    /* Open Flash_HP */
    err = R_OSPI_W_Open(&user_ospi_ctrl, &g_qspi_cfg);

    /* Handle Error */
    if (FSP_SUCCESS != err)
    {
        LOG_ERR("R_OSPI_W_Open Failed\r\n");
    }

    return err;
}

static void close_qspi(void)
{
    fsp_err_t error = FSP_SUCCESS;

    LOG_INFO("\r\n ** Closing QSPI module ** \r\n");

    /* close QSPI module */
    error = R_OSPI_W_Close(&user_ospi_ctrl);
    if (FSP_SUCCESS != error)
    {
        LOG_ERR("R_OSPI_W_Close Failed\r\n");
    }
}

#if BSP_TZ_SECURE_BUILD
FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{
}
FSP_CPP_FOOTER
#endif
